on: pull_request
name: team-label
jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v0.1.1
      with:
        repo-token: "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"
